version: 2
jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build image
          command: |
            docker build -t coorde/urdfdev .
      - run:
          name: Push
          command: |
            docker push coorde/urdfdev
